# Directory where tn source can be found (no trailing slash)
tn_dir: "/home/oliverc/shared/repos/en_tn_condensed"

# Book ids to render.  If empty, render all books.
# e.g. book_ids: ["mat", "tit"] # Just Matthew and Titus
# e.g. book_ids: []             # All books
book_ids: ["mat","luk","gal"]
